### PR TITLE
HTTP retrying

### LINKED ISSUE #30: Wait and retry failed HTTP requests

### PR DESCRIPTION
**Pull request by tylerfanelli**
A draft of closing Issue #30. 5 HTTP retries before failing and calling panic!()

Closes #30

### CODE REVIEW

**Review by npmccallum — CHANGES_REQUESTED** [review]
Could you rebase and squash the commits? Also, `cargo fmt` is failing.

File: src/main.rs [hunk 1]
```diff
@@ -154,16 +154,34 @@ enum Sevctl {
...
-    ))?;
+        // There is only a max of 5 HTTP requests allowed, if success is not reached within 5
+        // attempts, terminate program with proper failure message.
+        if http_request_count < 5 {
+            std::thread::sleep(std::time::Duration::new(time_wait_seconds, 0));
+            time_wait_seconds += 3;
+            let retry = reqwest::blocking::get(url);
+            rsp = retry.context(format!("unable to contact {} server", usage))?;
+        } else {
+                panic!("received failure from {} server: {}", usage, rsp_status);
```
Comment (connorkuehl) [inline src/main.rs]: Don't panic. Return an error. There's a method called `context` that you can call on `Result` types to add a more human-readable error message on top of the error that you encountered.

File: src/main.rs [hunk 2]
```diff
@@ -154,16 +154,34 @@ enum Sevctl {
...
+    let mut rsp = rsp.context(format!("unable to contact {} server", usage))?;
+    let _status = loop {
+
+        let rsp_status = rsp.status();
+        if rsp_status.is_success() {
+            break rsp_status;
+        } else if rsp_status.is_client_error() {
+            http_request_count += 1;
+        }
+
```
Comment (connorkuehl) [inline src/main.rs]: Seems like a lot of state to keep track of. Consider factoring out a helper function that takes a url as its input and returns a `reqwest::Result<reqwest::blocking::Response>`. Then you can have the initial download function call this helper and manage the retries independently from the function that actually performs the HTTP request. Does that sound reasonable?

I.e., just as an example:

```rust
use std::time::Duration;

fn make_request() -> std::io::Result<()> {
    let even = rand::random::<u32>() % 2 == 0;

    if even {
        Ok(())
    } else {
        Err(std::io::ErrorKind::TimedOut.into())
    }
}

fn main() {
    for timeout in &[0, 1, 2, 3, 4] {
        std::thread::sleep(Duration::from_secs(*timeout));

        match make_request() {
            Ok(_) => {
                println!("yay!");
                break;
            }
            Err(_) => println!("oops! retrying."),
        }
    }
}
```

I.e., in this example there's 1 function that knows exactly how to make an HTTP request, and its caller knows exactly to simply retry the request if there was an error.

**Review by connorkuehl — CHANGES_REQUESTED** [review]

File: src/main.rs (hunk 2 above)
Comment (tylerfanelli) [reply src/main.rs]: I see what you mean, will submit a change.

**Comment by connorkuehl** [comment]
@tfanelli-rh Also, please take care in writing your commit messages. There are [a few characteristics that make up a great commit message](https://chris.beams.io/posts/git-commit/) that other developers will find useful when reviewing your code or checking the history of the repository.

File: src/main.rs [hunk 3]
```diff
@@ -153,16 +153,30 @@ enum Sevctl {
...
-    rsp: reqwest::Result<reqwest::blocking::Response>,
-    usage: Usage,
-) -> Result<sev::Certificate> {
-    let rsp = rsp.context(format!("unable to contact {} server", usage))?;
-
-    let status = rsp.status();
-    let mut rsp = rsp.error_for_status().context(&format!(
-        "received failure from {} server: {}",
-        usage, status
+use std::time::Duration;
```
Comment (connorkuehl) [inline src/main.rs]: Please move this up with the other imports from the `std` lib.

File: src/main.rs [hunk 4]
```diff
@@ -153,16 +153,30 @@ enum Sevctl {
...
+
+fn download(url: &str, usage: Usage) -> Result<sev::Certificate> {
+    let mut rsp = reqwest::blocking::get(url);
+    for request_wait_seconds in &[0, 2, 4, 6, 9] {
+        std::thread::sleep(Duration::from_secs(*request_wait_seconds));
+        match &rsp {
+            // Connection is established, ensure that status code is not an error.
+            Ok(found) => {
```
Comment (connorkuehl) [inline src/main.rs]: This comment is a little misleading since as I understand it, the `reqwest::blocking::get()` is a one-shot HTTP request, meaning that we don't technically establish & maintain a connection after it's been called.

It would be more appropriate to write something about how the HTTP request appears to have succeeded, and we're just checking for an OK status code.

File: src/main.rs [hunk 5]
```diff
@@ -153,16 +153,30 @@ enum Sevctl {
...
+                if found.status().is_success() {
+                    break;
+                } else {
+                    rsp = reqwest::blocking::get(url);
+                }
+            }
+            // Connection not established, retry.
+            Err(_) => {
+                rsp = reqwest::blocking::get(url);
+            }
```
Comment (connorkuehl) [inline src/main.rs]: When reading the documentation for [`reqwest::blocking::get`](https://docs.rs/reqwest/0.11.3/reqwest/blocking/fn.get.html), it lists the following as possible reasons why it will return `Err`:

* native TLS backend cannot be initialized
* supplied Url cannot be parsed
* there was an error while sending request
* redirect loop was detected
* redirect limit was exhausted

These don't seem like problems that will solve themselves if we retry. I would argue we probably aren't interested in retrying here. We should just propagate the error down.

File: src/main.rs [hunk 6]
```diff
@@ -153,16 +153,30 @@ enum Sevctl {
...
+        }
+    }
+    let mut rsp = rsp.context(format!(
+        "After 5 attempts, unable to contact {} server",
+        usage
```
Comment (connorkuehl) [inline src/main.rs]: This isn't very actionable for the user. Furthermore, if we update the number of attempts we'll have to remember to update this message. I think since we are potentially retrying multiple times and we may get different non-200 HTTP replies, it might be a good idea to have a Vec<String> that we push the HTTP reply's error message to each time we decide we have to retry. Then we could include this information which the end user might find helpful if they need to file a bug report.

I.e., we could change this to:

```rust
let mut rsp = rsp.context("contacting {} server failed:\n{}", usage, retried_replies.join("\n"))?;
```

**Review by connorkuehl — CHANGES_REQUESTED** [review]
@tfanelli-rh Just a couple of comments, but otherwise great work! I tested this on an EPYC server and it works like a charm. I just ran `sevctl verify` over and over until I got ratelimited and saw sevctl backing off and retrying.

**Review by connorkuehl — DISMISSED** [review]
Thank you! :+1:

**Review by connorkuehl — APPROVED** [review]
It looks like you already saw why, but in the future I recommend using different branches for different PRs and just keeping the main branch in sync with the upstream main branch (if you use it at all) :slightly_smiling_face:

**Review by connorkuehl — CHANGES_REQUESTED** [review]
Sorry, I noticed this issue on a different PR too. Please sign your commit and force push again.

`git commit --amend -s`

**Review by connorkuehl — APPROVED** [review]

**Review by npmccallum — APPROVED** [review]
